# Programming for Data Analysis Project 2019



## Problem Statement

Create a data set by simulating a real-word phenomenon. Rather than collect data associated with the choosen real-world phenomenon the data should be modeled and synthesise the data using Python **numpy.randon** package



## ECAS Call Centre

The real world phenomenon we will be looking at is the Irish Emergency Call Answering Service (ECAS). This is a 24hr 365 day a year service.

References: 
https://www.dccae.gov.ie/en-ie/news-and-media/press-releases/Pages/Minister-Denis-Naughten-Publishes-New-Figures-on-Ireland%E2%80%99s-Emergency-Call-Answering-Service.aspx

References
https://towardsdatascience.com/learning-to-simulate-c53d8b393a56


## Real world phenomenon simulated

The real-world pheomenon choose to simulate is an emergency call answering service or ecas. The call centre will have the following variables and is open 24 hours 7 days a week and 365 days of the year

1. period_week
2. garda
3. fire
4. ambulance
5. coast_guard
6. total_calls

To simulate the call centre we are going to use the Poisson Distribution. This distrbution is used to model 

References: 
https://en.wikipedia.org/wiki/Poisson_distribution


In [1]:
#The following Python packages are imported
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# The period of a week is choosen starting from the 1st December 2019, the week is divided up in to hourly periods.
period_week =  pd.date_range('01-01-2018', '31-12-2018', freq='H')

#Reference: 
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html
#https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html

In [3]:
#period_week datetime index is printed out
period_week

DatetimeIndex(['2018-01-01 00:00:00', '2018-01-01 01:00:00',
               '2018-01-01 02:00:00', '2018-01-01 03:00:00',
               '2018-01-01 04:00:00', '2018-01-01 05:00:00',
               '2018-01-01 06:00:00', '2018-01-01 07:00:00',
               '2018-01-01 08:00:00', '2018-01-01 09:00:00',
               ...
               '2018-12-30 15:00:00', '2018-12-30 16:00:00',
               '2018-12-30 17:00:00', '2018-12-30 18:00:00',
               '2018-12-30 19:00:00', '2018-12-30 20:00:00',
               '2018-12-30 21:00:00', '2018-12-30 22:00:00',
               '2018-12-30 23:00:00', '2018-12-31 00:00:00'],
              dtype='datetime64[ns]', length=8737, freq='H')

In [4]:
#Define a random integer for the Poisson distrubution lamda value for calls for a garda emergency.
garda_randomint = np.random.randint(10,22)
garda_randomint

#Reference: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

19

In [5]:
#Construct the ecas_garda dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is again the time_period time index variable.
# The resulting poisson distribution values are labelled "garda"
ecas_garda = pd.DataFrame(np.random.poisson(garda_randomint, len(period_week)), index=period_week, columns=["garda"])
ecas_garda.head()

#Reference: 
#https://web.microsoftstream.com/video/db8801fe-9e42-4663-a508-5d6f38bb7327
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.poisson.html

garda
2018-01-01 00:00:00     19
2018-01-01 01:00:00     22
2018-01-01 02:00:00     15
2018-01-01 03:00:00     16
2018-01-01 04:00:00     20

In [6]:
#Define a random integer for the Poisson distrubution lamda value for calls for a fire emergency call.
fire_randomint = np.random.randint(10,17)
fire_randomint

#Reference: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

11

In [7]:
#Construct the ecas_fire dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is again the time_period time index variable.
# The resulting poisson distribution values are labelled "fire"
ecas_fire = pd.DataFrame(np.random.poisson(fire_randomint, len(period_week)), index=period_week, columns=["fire"])
ecas_fire.head()

#Reference: 
#https://web.microsoftstream.com/video/db8801fe-9e42-4663-a508-5d6f38bb7327
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.poisson.html

fire
2018-01-01 00:00:00     6
2018-01-01 01:00:00     8
2018-01-01 02:00:00    11
2018-01-01 03:00:00     7
2018-01-01 04:00:00     9

In [8]:
#Define a random integer for the Poisson distrubution lamda value for calls for a ambulance emergency call.
ambulance_randomint = np.random.randint(10,15)
ambulance_randomint

#Reference: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

11

In [9]:
#Construct the ecas_ambulance dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is the time_period time index variable.
# The resulting poisson distribution values are labelled "ambulance"
ecas_ambulance = pd.DataFrame(np.random.poisson(ambulance_randomint, len(period_week)), index=period_week, columns=["ambulance"])
ecas_ambulance.head()

#Reference: 
#https://web.microsoftstream.com/video/db8801fe-9e42-4663-a508-5d6f38bb7327
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.poisson.html

ambulance
2018-01-01 00:00:00         14
2018-01-01 01:00:00         12
2018-01-01 02:00:00         15
2018-01-01 03:00:00         15
2018-01-01 04:00:00         13

In [10]:
#Define a random integer for the Poisson distrubution lamda value for calls for a coast_guard emergency call.
coast_guard_randomint = np.random.randint(10,15)
coast_guard_randomint

#Reference: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

13

In [11]:
#Construct the ecas_coast_guard dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is the time_period time index variable.
# The resulting poisson distribution values are labelled "coast_guard"
ecas_coast_guard = pd.DataFrame(np.random.poisson(coast_guard_randomint, len(period_week)), index=period_week, columns=["coast_guard"])
ecas_coast_guard.head()

#Reference: 
#https://web.microsoftstream.com/video/db8801fe-9e42-4663-a508-5d6f38bb7327
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.poisson.html

coast_guard
2018-01-01 00:00:00           14
2018-01-01 01:00:00           17
2018-01-01 02:00:00            7
2018-01-01 03:00:00           13
2018-01-01 04:00:00           16

In [12]:
ecas = ecas_garda
ecas.head()

garda
2018-01-01 00:00:00     19
2018-01-01 01:00:00     22
2018-01-01 02:00:00     15
2018-01-01 03:00:00     16
2018-01-01 04:00:00     20

In [13]:
# Creating an array of values from the Dataframe ecas_fire
# Reference: https://stackoverflow.com/questions/46396257/adding-a-new-column-in-pandas-dataframe-from-another-dataframe-with-differing-in
ecas_fire['fire'].values

array([ 6,  8, 11, ...,  8,  9, 11])

In [14]:
ecas_ambulance['ambulance'].values

array([14, 12, 15, ..., 15, 17,  7])

In [15]:
# Adding the fire columns to the ecas Dataframe, the ecas columns will consist of police and fire
ecas['fire'] = ecas_fire['fire'].values
ecas.head()

garda  fire
2018-01-01 00:00:00     19     6
2018-01-01 01:00:00     22     8
2018-01-01 02:00:00     15    11
2018-01-01 03:00:00     16     7
2018-01-01 04:00:00     20     9

In [16]:
# Creating an array of values from the Dataframe ecas_ambulance
# Reference: https://stackoverflow.com/questions/46396257/adding-a-new-column-in-pandas-dataframe-from-another-dataframe-with-differing-in
ecas['ambulance'] = ecas_ambulance['ambulance'].values
ecas.head()

garda  fire  ambulance
2018-01-01 00:00:00     19     6         14
2018-01-01 01:00:00     22     8         12
2018-01-01 02:00:00     15    11         15
2018-01-01 03:00:00     16     7         15
2018-01-01 04:00:00     20     9         13

In [17]:
# Adding the ambulance columns to the ecas Dataframe, the ecas columns will consist of garda, fire and ambulance
ecas['ambulance'] = ecas_ambulance['ambulance'].values
ecas.head()

garda  fire  ambulance
2018-01-01 00:00:00     19     6         14
2018-01-01 01:00:00     22     8         12
2018-01-01 02:00:00     15    11         15
2018-01-01 03:00:00     16     7         15
2018-01-01 04:00:00     20     9         13

In [18]:
# Creating an array of values from the Dataframe ecas_coast_guard
# Reference: https://stackoverflow.com/questions/46396257/adding-a-new-column-in-pandas-dataframe-from-another-dataframe-with-differing-in
ecas_coast_guard['coast_guard'].values

array([14, 17,  7, ..., 12, 23, 18])

In [19]:
# Adding the coast_guard column to the ecas Dataframe, the ecas columns will consist of garda, fire, ambulance and coast_guard
ecas['coast_guard'] = ecas_coast_guard['coast_guard'].values
ecas.head()

garda  fire  ambulance  coast_guard
2018-01-01 00:00:00     19     6         14           14
2018-01-01 01:00:00     22     8         12           17
2018-01-01 02:00:00     15    11         15            7
2018-01-01 03:00:00     16     7         15           13
2018-01-01 04:00:00     20     9         13           16

In [20]:
# Sum columns garda, fire, ambulance, coast_guard to give a new column total_calls
# Reference: https://stackoverflow.com/questions/34023918/make-new-column-in-panda-dataframe-by-adding-values-from-other-columns/34023971
ecas['total_calls'] = ecas['garda'] + ecas['fire'] + ecas['ambulance'] + ecas['coast_guard']
ecas

garda  fire  ambulance  coast_guard  total_calls
2018-01-01 00:00:00     19     6         14           14           53
2018-01-01 01:00:00     22     8         12           17           59
2018-01-01 02:00:00     15    11         15            7           48
2018-01-01 03:00:00     16     7         15           13           51
2018-01-01 04:00:00     20     9         13           16           58
2018-01-01 05:00:00     12     7         12           15           46
2018-01-01 06:00:00     21     9          9           12           51
2018-01-01 07:00:00     19    11         10           16           56
2018-01-01 08:00:00     11    12         17            9           49
2018-01-01 09:00:00     19     9          9           18           55
2018-01-01 10:00:00     12    11          8           19           50
2018-01-01 11:00:00     13    12         14           11           50
2018-01-01 12:00:00     17     8         11           18           54
2018-01-01 13:00:00     11     9          8           10           38
2018-01-01 14:00:00     23     8         22           16           69
2018-01-01 15:00:00     20    13         17           11           61
2018-01-01 16:00:00     15    13         13           10           51
2018-01-01 17:00:00     23     8          4           18           53
2018-01-01 18:00:00     17    19         11           14           61
2018-01-01 19:00:00     15    11          7           14           47
2018-01-01 20:00:00     21    10         12           11           54
2018-01-01 21:00:00     19    10          8           13           50
2018-01-01 22:00:00     25    17         16           10           68
2018-01-01 23:00:00     11    11          6            8           36
2018-01-02 00:00:00     22    10         11           10           53
2018-01-02 01:00:00     16    10          5           15           46
2018-01-02 02:00:00     33     9          8           11           61
2018-01-02 03:00:00     18     7         10           17           52
2018-01-02 04:00:00     21     5         10           20           56
2018-01-02 05:00:00     17    16          8           10           51
...                    ...   ...        ...          ...          ...
2018-12-29 19:00:00     23    13         13           15           64
2018-12-29 20:00:00     28    15          9           12           64
2018-12-29 21:00:00     18     9          9           10           46
2018-12-29 22:00:00     26    15         16           14           71
2018-12-29 23:00:00     23    13         19           10           65
2018-12-30 00:00:00     14    14          9           10           47
2018-12-30 01:00:00     26    13         12           17           68
2018-12-30 02:00:00     19    14         10           13           56
2018-12-30 03:00:00     14    12          9           16           51
2018-12-30 04:00:00     14    18          6            8           46
2018-12-30 05:00:00     20     9         10            6           45
2018-12-30 06:00:00     15    12          7           10           44
2018-12-30 07:00:00     15     7          6           20           48
2018-12-30 08:00:00     12    14          9            9           44
2018-12-30 09:00:00     18     8         12           12           50
2018-12-30 10:00:00     20    10         17           13           60
2018-12-30 11:00:00     21    13         16           11           61
2018-12-30 12:00:00     21    13         12           14           60
2018-12-30 13:00:00     23    15         11           16           65
2018-12-30 14:00:00     18    14         11           19           62
2018-12-30 15:00:00     16    14          7           17           54
2018-12-30 16:00:00     26    10         11           16           63
2018-12-30 17:00:00     16    12          9           13           50
2018-12-30 18:00:00     20    12         14            7           53
2018-12-30 19:00:00     18    13         14           17           62
2018-12-30 20:00:00     19     

In [21]:
ecas['total_calls'].sum()

471624

## Average Call Duration

The average ECAS call duration is 7.57 in 2017 according to the Department of environment website below.

I this section we will build this in to out model to simulate how many agents need to be available so that no call is queued. 

There will be two more variables added to the ecas dataframe

1. total_avg_talk_time
2. agents_required

Reference: 
https://www.dccae.gov.ie/en-ie/news-and-media/press-releases/Pages/Minister-Denis-Naughten-Publishes-New-Figures-on-Ireland%E2%80%99s-Emergency-Call-Answering-Service.aspx

### Add talk_time and agent_required

The next section of code will add in talk_time and agents_required to the ecas dataframe.

In [22]:
ecas['total_avg_talk_time'] = ecas['total_calls'] * 8
ecas.head()

garda  fire  ambulance  coast_guard  total_calls  \
2018-01-01 00:00:00     19     6         14           14           53   
2018-01-01 01:00:00     22     8         12           17           59   
2018-01-01 02:00:00     15    11         15            7           48   
2018-01-01 03:00:00     16     7         15           13           51   
2018-01-01 04:00:00     20     9         13           16           58   

                     total_avg_talk_time  
2018-01-01 00:00:00                  424  
2018-01-01 01:00:00                  472  
2018-01-01 02:00:00                  384  
2018-01-01 03:00:00                  408  
2018-01-01 04:00:00                  464

In [23]:
ecas_jan = ecas.loc['2018-01-01':'2018-01-31']
ecas_jan.head()

garda  fire  ambulance  coast_guard  total_calls  \
2018-01-01 00:00:00     19     6         14           14           53   
2018-01-01 01:00:00     22     8         12           17           59   
2018-01-01 02:00:00     15    11         15            7           48   
2018-01-01 03:00:00     16     7         15           13           51   
2018-01-01 04:00:00     20     9         13           16           58   

                     total_avg_talk_time  
2018-01-01 00:00:00                  424  
2018-01-01 01:00:00                  472  
2018-01-01 02:00:00                  384  
2018-01-01 03:00:00                  408  
2018-01-01 04:00:00                  464

In [24]:
ecas_jan['total_calls'].sum()

39826

In [25]:
ecas_jan.head()

garda  fire  ambulance  coast_guard  total_calls  \
2018-01-01 00:00:00     19     6         14           14           53   
2018-01-01 01:00:00     22     8         12           17           59   
2018-01-01 02:00:00     15    11         15            7           48   
2018-01-01 03:00:00     16     7         15           13           51   
2018-01-01 04:00:00     20     9         13           16           58   

                     total_avg_talk_time  
2018-01-01 00:00:00                  424  
2018-01-01 01:00:00                  472  
2018-01-01 02:00:00                  384  
2018-01-01 03:00:00                  408  
2018-01-01 04:00:00                  464

In [26]:
ecas[ecas.index.month == 1]['total_calls'].sum()

39826

In [27]:
ecas[ecas.index == '2018-01-01 00:00:00']['total_calls'].values

array([53])

### Poisson Probability

The poisson probability of a call arriving in a particular interval can be calculated as follows:


In [28]:

from scipy.special import factorial

time_p = '2018-01-01 00:00:00'

calls_per_min = ecas[ecas.index == time_p]['total_calls'].values/60

minutes = 5

# Expected events
lam = calls_per_min[0] * minutes

k = 2
pk = np.exp(-lam) * np.power(lam, k) / factorial(k)
print(f'The probability of {k} calls in {minutes} minutes is {100*pk:.2f}% for the time period {time_p}')

#Reference: https://github.com/WillKoehrsen/Data-Analysis/blob/master/poisson/poisson.ipynb

The probability of 2 calls in 5 minutes is 11.78% for the time period 2018-01-01 00:00:00
