# Programming for Data Analysis Project 2019



## Problem Statement

Create a data set by simulating a real-word phenomenon. Rather than collect data associated with the choosen real-world phenomenon the data should be modeled and synthesise the data using Python **numpy.randon** package



References
https://towardsdatascience.com/learning-to-simulate-c53d8b393a56


## Real world phenomenon simulated

The real-world pheomenon choose to simulate is an emergency call answering service or ecas. The call centre will have the following variables and is open 24 hours 7 days a week and 365 days of the year

1. period_week
2. police
3. fire
4. ambulance
5. total_calls



In [1]:
#The following Python packages are imported
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# The period of a week is choosen starting from the 1st December 2019, the week is diided up in to hourly periods.
period_week =  pd.date_range('01-01-2019', '31-12-2019', freq='H')

#Reference: 
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html
#https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html

In [3]:
#period_week datetime index is printed out
period_week

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               ...
               '2019-12-30 15:00:00', '2019-12-30 16:00:00',
               '2019-12-30 17:00:00', '2019-12-30 18:00:00',
               '2019-12-30 19:00:00', '2019-12-30 20:00:00',
               '2019-12-30 21:00:00', '2019-12-30 22:00:00',
               '2019-12-30 23:00:00', '2019-12-31 00:00:00'],
              dtype='datetime64[ns]', length=8737, freq='H')

In [4]:
#Define a random integer for the Poisson distrubution lamda value for calls for a police emergency.
police_randomint = np.random.randint(0,22)
police_randomint

2

In [20]:
#Construct the ecas_police dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is again the time_period time index variable.
# The resulting poisson distribution values are labelled "police"
ecas_police = pd.DataFrame(np.random.poisson(police_randomint, len(period_week)), index=period_week, columns=["police"])
ecas_police.head()

police
2019-01-01 00:00:00       0
2019-01-01 01:00:00       0
2019-01-01 02:00:00       3
2019-01-01 03:00:00       1
2019-01-01 04:00:00       2

In [6]:
#Define a random integer for the Poisson distrubution lamda value for calls for a fire emergency.
fire_randomint = np.random.randint(1,7)
fire_randomint

2

In [7]:
#Construct the ecas_fire dataframe using Numpy random.poisson function in Python. The length of the dataframe is the amount
#time intervals in the time_period defined above. The index of the Dataframe is again the time_period time index variable.
# The resulting poisson distribution values are labelled "police"
ecas_fire = pd.DataFrame(np.random.poisson(fire_randomint, len(period_week)), index=period_week, columns=["fire"])
ecas_fire.head()


fire
2019-01-01 00:00:00     1
2019-01-01 01:00:00     1
2019-01-01 02:00:00     1
2019-01-01 03:00:00     3
2019-01-01 04:00:00     3

In [8]:
ambulance_randomint = np.random.randint(1,15)
ambulance_randomint

1

In [9]:

ecas_ambulance = pd.DataFrame(np.random.poisson(ambulance_randomint, len(period_week)), index=period_week, columns=["ambulance"])
ecas_ambulance.head()

ambulance
2019-01-01 00:00:00          2
2019-01-01 01:00:00          2
2019-01-01 02:00:00          1
2019-01-01 03:00:00          3
2019-01-01 04:00:00          1

In [11]:
# Creating an array of values from the Dataframe ecas_ambulance
# Reference: https://stackoverflow.com/questions/46396257/adding-a-new-column-in-pandas-dataframe-from-another-dataframe-with-differing-in
ecas_ambulance['ambulance'].values

array([2, 2, 1, ..., 0, 3, 0])

In [12]:
#Adding the values to the existing joined array
ecaspolicefire['ambulance'] = ecas_ambulance['ambulance'].values


In [13]:
ecas = ecas_police
ecas.head()

police
2019-01-01 00:00:00       1
2019-01-01 01:00:00       0
2019-01-01 02:00:00       4
2019-01-01 03:00:00       4
2019-01-01 04:00:00       1

In [14]:
ecas_fire['fire'].values

array([1, 1, 1, ..., 4, 3, 0])

In [15]:
ecas_ambulance['ambulance'].values

array([2, 2, 1, ..., 0, 3, 0])

In [16]:
ecas['fire'] = ecas_fire['fire'].values
ecas.head()

police  fire
2019-01-01 00:00:00       1     1
2019-01-01 01:00:00       0     1
2019-01-01 02:00:00       4     1
2019-01-01 03:00:00       4     3
2019-01-01 04:00:00       1     3

In [17]:
ecas['ambulance'] = ecas_ambulance['ambulance'].values
ecas.head()

police  fire  ambulance
2019-01-01 00:00:00       1     1          2
2019-01-01 01:00:00       0     1          2
2019-01-01 02:00:00       4     1          1
2019-01-01 03:00:00       4     3          3
2019-01-01 04:00:00       1     3          1

In [18]:
# Sum columns police, fire, ambulance to give total_calls
# Reference: https://stackoverflow.com/questions/34023918/make-new-column-in-panda-dataframe-by-adding-values-from-other-columns/34023971
#df['C'] = df['A'] + df['B']

In [19]:
# Sum columns police, fire, ambulance to give total_calls
# Reference: https://stackoverflow.com/questions/34023918/make-new-column-in-panda-dataframe-by-adding-values-from-other-columns/34023971
ecas['total_calls'] = ecas['police'] + ecas['fire'] + ecas['ambulance']
ecas

police  fire  ambulance  total_calls
2019-01-01 00:00:00       1     1          2            4
2019-01-01 01:00:00       0     1          2            3
2019-01-01 02:00:00       4     1          1            6
2019-01-01 03:00:00       4     3          3           10
2019-01-01 04:00:00       1     3          1            5
2019-01-01 05:00:00       1     7          1            9
2019-01-01 06:00:00       0     1          1            2
2019-01-01 07:00:00       1     3          1            5
2019-01-01 08:00:00       2     5          3           10
2019-01-01 09:00:00       2     1          0            3
2019-01-01 10:00:00       2     2          0            4
2019-01-01 11:00:00       2     2          3            7
2019-01-01 12:00:00       1     2          0            3
2019-01-01 13:00:00       2     1          5            8
2019-01-01 14:00:00       1     3          2            6
2019-01-01 15:00:00       2     1          1            4
2019-01-01 16:00:00       1     1          0            2
2019-01-01 17:00:00       2     1          1            4
2019-01-01 18:00:00       0     1          1            2
2019-01-01 19:00:00       4     0          1            5
2019-01-01 20:00:00       3     3          2            8
2019-01-01 21:00:00       1     2          1            4
2019-01-01 22:00:00       4     2          0            6
2019-01-01 23:00:00       1     2          0            3
2019-01-02 00:00:00       3     2          3            8
2019-01-02 01:00:00       0     1          1            2
2019-01-02 02:00:00       1     2          1            4
2019-01-02 03:00:00       2     0          0            2
2019-01-02 04:00:00       3     1          2            6
2019-01-02 05:00:00       3     0          1            4
...                     ...   ...        ...          ...
2019-12-29 19:00:00       2     1          1            4
2019-12-29 20:00:00       2     3          3            8
2019-12-29 21:00:00       0     1          1            2
2019-12-29 22:00:00       2     4          2            8
2019-12-29 23:00:00       3     0          2            5
2019-12-30 00:00:00       1     1          0            2
2019-12-30 01:00:00       2     0          1            3
2019-12-30 02:00:00       2     3          1            6
2019-12-30 03:00:00       2     2          0            4
2019-12-30 04:00:00       3     2          0            5
2019-12-30 05:00:00       1     4          1            6
2019-12-30 06:00:00       7     2          4           13
2019-12-30 07:00:00       1     3          0            4
2019-12-30 08:00:00       1     2          0            3
2019-12-30 09:00:00       3     4          0            7
2019-12-30 10:00:00       1     3          1            5
2019-12-30 11:00:00       1     3          1            5
2019-12-30 12:00:00       3     1          1            5
2019-12-30 13:00:00       1     1          2            4
2019-12-30 14:00:00       2     3          3            8
2019-12-30 15:00:00       4     0          0            4
2019-12-30 16:00:00       3     1          1            5
2019-12-30 17:00:00       3     2          0            5
2019-12-30 18:00:00       1     1          0            2
2019-12-30 19:00:00       1     1          2            4
2019-12-30 20:00:00       0     3          0            3
2019-12-30 21:00:00       1     2          2            5
2019-12-30 22:00:00       4     4          0            8
2019-12-30 23:00:00       1     3          3            7
2019-12-31 00:00:00       1     0          0            1

[8737 rows x 4 columns]