# Programming for Data Analysis Project 2019



## Problem Statement

Create a data set by simulating a real-word phenomenon. Rather than collect data associated with the choosen real-world phenomenon the data should be modeled and synthesise the data using Python **numpy.randon** package



References
https://towardsdatascience.com/learning-to-simulate-c53d8b393a56


## Real world phenomenon simulated

The real-world pheomenon choose to simulate is a call centre. The call centre will have the following variables

1. period_week
2. callsinbound
3. agents
4. callqueues



In [1]:
#A number is Python packages are imported

import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#Variable 1 is a timeseries variable 

timep = pd.timedelta_range('09:00:00', periods=9, freq="H")

# Reference: 
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html
#https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html

In [3]:
dates = pd.date_range('2019-12-01', periods=10, freq='B')


In [4]:
dates[0]

Timestamp('2019-12-02 00:00:00', freq='B')

In [5]:
period_week =  pd.date_range('2019-12-01', periods=168, freq='H')


In [6]:
period_week

DatetimeIndex(['2019-12-01 00:00:00', '2019-12-01 01:00:00',
               '2019-12-01 02:00:00', '2019-12-01 03:00:00',
               '2019-12-01 04:00:00', '2019-12-01 05:00:00',
               '2019-12-01 06:00:00', '2019-12-01 07:00:00',
               '2019-12-01 08:00:00', '2019-12-01 09:00:00',
               ...
               '2019-12-07 14:00:00', '2019-12-07 15:00:00',
               '2019-12-07 16:00:00', '2019-12-07 17:00:00',
               '2019-12-07 18:00:00', '2019-12-07 19:00:00',
               '2019-12-07 20:00:00', '2019-12-07 21:00:00',
               '2019-12-07 22:00:00', '2019-12-07 23:00:00'],
              dtype='datetime64[ns]', length=168, freq='H')

In [7]:
#open = openhrs.between_time("9:00", "17:00")

In [8]:
period_week[0]

Timestamp('2019-12-01 00:00:00', freq='H')

In [9]:
x = np.random.randint(0,7)
ecas = pd.DataFrame(np.random.poisson(x, len(period_week)), index=period_week, columns=["callsinbound"])


In [10]:
ecas.head()

callsinbound
2019-12-01 00:00:00             5
2019-12-01 01:00:00             7
2019-12-01 02:00:00             4
2019-12-01 03:00:00             7
2019-12-01 04:00:00             7

In [11]:
ecas.iloc[2 : 10]

callsinbound
2019-12-01 02:00:00             4
2019-12-01 03:00:00             7
2019-12-01 04:00:00             7
2019-12-01 05:00:00            12
2019-12-01 06:00:00             6
2019-12-01 07:00:00             8
2019-12-01 08:00:00             4
2019-12-01 09:00:00             2

In [12]:
ecas.loc[:,'callsinbound']

2019-12-01 00:00:00     5
2019-12-01 01:00:00     7
2019-12-01 02:00:00     4
2019-12-01 03:00:00     7
2019-12-01 04:00:00     7
2019-12-01 05:00:00    12
2019-12-01 06:00:00     6
2019-12-01 07:00:00     8
2019-12-01 08:00:00     4
2019-12-01 09:00:00     2
2019-12-01 10:00:00     4
2019-12-01 11:00:00     9
2019-12-01 12:00:00     6
2019-12-01 13:00:00     9
2019-12-01 14:00:00     6
2019-12-01 15:00:00     7
2019-12-01 16:00:00     8
2019-12-01 17:00:00     5
2019-12-01 18:00:00     3
2019-12-01 19:00:00     8
2019-12-01 20:00:00     5
2019-12-01 21:00:00     8
2019-12-01 22:00:00     4
2019-12-01 23:00:00     3
2019-12-02 00:00:00    13
2019-12-02 01:00:00    10
2019-12-02 02:00:00     4
2019-12-02 03:00:00     7
2019-12-02 04:00:00     9
2019-12-02 05:00:00     8
                       ..
2019-12-06 18:00:00    11
2019-12-06 19:00:00     6
2019-12-06 20:00:00     4
2019-12-06 21:00:00     1
2019-12-06 22:00:00     1
2019-12-06 23:00:00     6
2019-12-07 00:00:00     5
2019-12-07 0

In [13]:
# DataFrame([data, index, columns, dtype, copy])
#ecas = pd.DataFrame(np.random.poisson(5, len(period_week)), index=period_week, columns=["callsinbound"])
#ecas2 = pd.DataFrame.add(ecas.loc[:,'callsinbound'],   index=period_week, columns=["agents"])

ecas = pd.DataFrame(np.random.poisson(5, len(period_week)), index=period_week, columns=["callsinbound"])

In [14]:
#working
#df = pd.DataFrame(np.random.randint(0,100, size=(168,4)), index=period_week, columns=list('ABCD'))

In [15]:
#Category = ["Police", "Fire", "Ambulance"]
#Category_Probability = np.random.choice(Category, 1, p=[0.15, 0.35, 0.50])
#Category_Probability

In [16]:
#data = {'Batch':Batch,'Target':Targets,'Status':Statuscallsinbounds,'Location':Locations,'Responsible':Responsibles}

dataset = {'callsinbound':ecas}

In [17]:
police_randomint = np.random.randint(0,22)
police_randomint

5

In [18]:
ecas_police = pd.DataFrame(np.random.poisson(police_randomint, len(period_week)), index=period_week, columns=["police"])
ecas_police.head()

police
2019-12-01 00:00:00       4
2019-12-01 01:00:00       4
2019-12-01 02:00:00       4
2019-12-01 03:00:00       7
2019-12-01 04:00:00       4

In [19]:
fire_randomint = np.random.randint(0,7)
fire_randomint

0

In [20]:

ecas_fire = pd.DataFrame(np.random.poisson(fire_randomint, len(period_week)), index=period_week, columns=["fire"])
ecas_fire.head()


fire
2019-12-01 00:00:00     0
2019-12-01 01:00:00     0
2019-12-01 02:00:00     0
2019-12-01 03:00:00     0
2019-12-01 04:00:00     0

In [21]:
ambulance_randomint = np.random.randint(0,15)
ambulance_randomint

7

In [22]:

ecas_ambulance = pd.DataFrame(np.random.poisson(ambulance_randomint, len(period_week)), index=period_week, columns=["ambulance"])
ecas_ambulance.head()

ambulance
2019-12-01 00:00:00          5
2019-12-01 01:00:00          5
2019-12-01 02:00:00          4
2019-12-01 03:00:00          8
2019-12-01 04:00:00         11

In [23]:
#df.join(other, lsuffix='_caller', rsuffix='_other')
ecaspolicefire = ecas_police.join(ecas_fire, lsuffix='police', rsuffix='fire')

ecaspolicefire.head()

police  fire
2019-12-01 00:00:00       4     0
2019-12-01 01:00:00       4     0
2019-12-01 02:00:00       4     0
2019-12-01 03:00:00       7     0
2019-12-01 04:00:00       4     0

In [24]:
# Creating an array of values from the Dataframe ecas_ambulance
# Reference: https://stackoverflow.com/questions/46396257/adding-a-new-column-in-pandas-dataframe-from-another-dataframe-with-differing-in
ecas_ambulance['ambulance'].values

array([ 5,  5,  4,  8, 11, 12,  9,  8,  8, 11, 10,  8,  3,  8,  4,  7,  9,
        8,  5,  8, 11,  6, 10,  7,  9,  6,  9, 10,  2,  4,  4,  4, 10,  9,
        5,  7,  6,  0,  7,  4,  7,  8,  5,  6,  8,  7,  5,  5,  7,  7,  6,
        4,  9,  2,  9, 10, 10, 12,  7,  8,  7,  9,  6, 10,  7,  6,  8, 10,
        9,  5,  8, 11, 13,  1,  6,  9,  5,  6,  4,  5,  5,  7,  6,  7,  9,
        8,  7,  3,  8,  3,  5,  7,  5,  8,  6,  8,  6,  7,  4, 10,  4, 11,
        7,  5,  3,  6,  3,  7, 10,  9, 13,  5,  2, 11,  8,  7,  7,  8,  9,
       10,  6,  7,  8,  6,  3,  5,  8,  7,  5,  8,  7,  5,  4,  4,  5,  9,
        5,  6,  3,  4,  3,  9,  3, 11,  7,  8,  8,  8,  9,  8,  5,  7,  8,
        7, 12,  7,  5,  6,  4,  6, 12,  3,  8, 11, 17, 11,  8,  6])

In [25]:
#Adding the values to the existing joined array
ecaspolicefire['ambulance'] = ecas_ambulance['ambulance'].values


In [26]:
ecas = ecas_police
ecas.head()

police
2019-12-01 00:00:00       4
2019-12-01 01:00:00       4
2019-12-01 02:00:00       4
2019-12-01 03:00:00       7
2019-12-01 04:00:00       4

In [27]:
ecas_fire['fire'].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
ecas_ambulance['ambulance'].values

array([ 5,  5,  4,  8, 11, 12,  9,  8,  8, 11, 10,  8,  3,  8,  4,  7,  9,
        8,  5,  8, 11,  6, 10,  7,  9,  6,  9, 10,  2,  4,  4,  4, 10,  9,
        5,  7,  6,  0,  7,  4,  7,  8,  5,  6,  8,  7,  5,  5,  7,  7,  6,
        4,  9,  2,  9, 10, 10, 12,  7,  8,  7,  9,  6, 10,  7,  6,  8, 10,
        9,  5,  8, 11, 13,  1,  6,  9,  5,  6,  4,  5,  5,  7,  6,  7,  9,
        8,  7,  3,  8,  3,  5,  7,  5,  8,  6,  8,  6,  7,  4, 10,  4, 11,
        7,  5,  3,  6,  3,  7, 10,  9, 13,  5,  2, 11,  8,  7,  7,  8,  9,
       10,  6,  7,  8,  6,  3,  5,  8,  7,  5,  8,  7,  5,  4,  4,  5,  9,
        5,  6,  3,  4,  3,  9,  3, 11,  7,  8,  8,  8,  9,  8,  5,  7,  8,
        7, 12,  7,  5,  6,  4,  6, 12,  3,  8, 11, 17, 11,  8,  6])

In [29]:
ecas['fire'] = ecas_fire['fire'].values
ecas.head()

police  fire
2019-12-01 00:00:00       4     0
2019-12-01 01:00:00       4     0
2019-12-01 02:00:00       4     0
2019-12-01 03:00:00       7     0
2019-12-01 04:00:00       4     0

In [30]:
ecas['ambulance'] = ecas_ambulance['ambulance'].values
ecas.head()

police  fire  ambulance
2019-12-01 00:00:00       4     0          5
2019-12-01 01:00:00       4     0          5
2019-12-01 02:00:00       4     0          4
2019-12-01 03:00:00       7     0          8
2019-12-01 04:00:00       4     0         11

In [31]:
# Sum columns police, fire, ambulance to give total_calls
# Reference: https://stackoverflow.com/questions/34023918/make-new-column-in-panda-dataframe-by-adding-values-from-other-columns/34023971
#df['C'] = df['A'] + df['B']

In [32]:
# Sum columns police, fire, ambulance to give total_calls
# Reference: https://stackoverflow.com/questions/34023918/make-new-column-in-panda-dataframe-by-adding-values-from-other-columns/34023971
ecas['total_calls'] = ecas['police'] + ecas['fire'] + ecas['ambulance']
ecas

police  fire  ambulance  total_calls
2019-12-01 00:00:00       4     0          5            9
2019-12-01 01:00:00       4     0          5            9
2019-12-01 02:00:00       4     0          4            8
2019-12-01 03:00:00       7     0          8           15
2019-12-01 04:00:00       4     0         11           15
2019-12-01 05:00:00       2     0         12           14
2019-12-01 06:00:00       2     0          9           11
2019-12-01 07:00:00       1     0          8            9
2019-12-01 08:00:00       4     0          8           12
2019-12-01 09:00:00       4     0         11           15
2019-12-01 10:00:00       4     0         10           14
2019-12-01 11:00:00       7     0          8           15
2019-12-01 12:00:00       4     0          3            7
2019-12-01 13:00:00      10     0          8           18
2019-12-01 14:00:00       1     0          4            5
2019-12-01 15:00:00       8     0          7           15
2019-12-01 16:00:00       5     0          9           14
2019-12-01 17:00:00      10     0          8           18
2019-12-01 18:00:00       5     0          5           10
2019-12-01 19:00:00       4     0          8           12
2019-12-01 20:00:00       4     0         11           15
2019-12-01 21:00:00       6     0          6           12
2019-12-01 22:00:00       7     0         10           17
2019-12-01 23:00:00       3     0          7           10
2019-12-02 00:00:00       3     0          9           12
2019-12-02 01:00:00       5     0          6           11
2019-12-02 02:00:00       6     0          9           15
2019-12-02 03:00:00       3     0         10           13
2019-12-02 04:00:00       5     0          2            7
2019-12-02 05:00:00       3     0          4            7
...                     ...   ...        ...          ...
2019-12-06 18:00:00       8     0          3           11
2019-12-06 19:00:00       3     0          4            7
2019-12-06 20:00:00       1     0          3            4
2019-12-06 21:00:00       4     0          9           13
2019-12-06 22:00:00       5     0          3            8
2019-12-06 23:00:00      10     0         11           21
2019-12-07 00:00:00       8     0          7           15
2019-12-07 01:00:00       1     0          8            9
2019-12-07 02:00:00       3     0          8           11
2019-12-07 03:00:00       7     0          8           15
2019-12-07 04:00:00       8     0          9           17
2019-12-07 05:00:00       7     0          8           15
2019-12-07 06:00:00       2     0          5            7
2019-12-07 07:00:00       6     0          7           13
2019-12-07 08:00:00       4     0          8           12
2019-12-07 09:00:00       5     0          7           12
2019-12-07 10:00:00       6     0         12           18
2019-12-07 11:00:00       3     0          7           10
2019-12-07 12:00:00       7     0          5           12
2019-12-07 13:00:00       4     0          6           10
2019-12-07 14:00:00       4     0          4            8
2019-12-07 15:00:00       6     0          6           12
2019-12-07 16:00:00       6     0         12           18
2019-12-07 17:00:00       4     0          3            7
2019-12-07 18:00:00       4     0          8           12
2019-12-07 19:00:00       5     0         11           16
2019-12-07 20:00:00       5     0         17           22
2019-12-07 21:00:00       3     0         11           14
2019-12-07 22:00:00       6     0          8           14
2019-12-07 23:00:00       4     0          6           10

[168 rows x 4 columns]